#!/usr/bin/env bash
# meta-skill prepare.sh v1
# Generated by meta-skill. Edit between the user-editable markers only.
# Rebuilds project-level skill symlinks based on the sentinel block in CLAUDE.md.
#
# Usage:
#   ./prepare.sh                                  # rebuild from CLAUDE.md sentinel
#   SENTINEL_FILE=AGENTS.md ./prepare.sh          # use AGENTS.md instead
#   SKILLSHARE_ROOT=/custom/path ./prepare.sh     # override source root
#
# Prereq: skillshare CLI installed (brew install skillshare) for best results.
# Falls back to $SKILLSHARE_ROOT directory scan if CLI missing.

set -euo pipefail

cd "$(dirname "$0")"
PROJECT_ROOT="$(pwd)"
SENTINEL_FILE="${SENTINEL_FILE:-CLAUDE.md}"
SKILLSHARE_ROOT="${SKILLSHARE_ROOT:-$HOME/.config/skillshare/skills}"
TARGET_DIRS=(".claude/skills" ".codex/skills" ".agents/skills")

# ---------- read sentinel block ----------

if [[ ! -f "$SENTINEL_FILE" ]]; then
  echo "ERROR: $SENTINEL_FILE not found in $PROJECT_ROOT" >&2
  echo "       meta-skill must have written the sentinel block first." >&2
  exit 1
fi

# Extract skill names from "### 项目级补充" section between meta-skill:begin and meta-skill:meta.
# Pattern: lines like "- `skill-name` — ..."
skills=$(awk '
  /<!-- meta-skill:begin -->/  { in_block=1; next }
  /<!-- meta-skill:meta -->/   { in_block=0; next }
  /<!-- meta-skill:end -->/    { in_block=0; next }
  in_block && /^### 项目级补充/ { in_project=1; next }
  in_block && /^### /          { in_project=0 }
  in_project && /^- `/ {
    if (match($0, /`[^`]+`/)) {
      print substr($0, RSTART+1, RLENGTH-2)
    }
  }
' "$SENTINEL_FILE")

if [[ -z "$skills" ]]; then
  echo "No project-level skills declared in $SENTINEL_FILE sentinel block."
  echo "Nothing to do."
  exit 0
fi

# ---------- prep target dirs ----------

for d in "${TARGET_DIRS[@]}"; do
  mkdir -p "$d"
done

# ---------- source resolver ----------

resolve_source() {
  local name="$1"

  # 1. skillshare CLI (preferred)
  # skillshare list --json is a FLAT array; each item has keys:
  # disabled/kind/name/relPath/repoName (NO .path). The real source dir is
  # $SKILLSHARE_ROOT/<relPath>, and the leaf skill name = basename of relPath.
  if command -v skillshare &>/dev/null && command -v jq &>/dev/null; then
    local relpath path
    relpath=$(skillshare list --json 2>/dev/null \
      | jq -r --arg n "$name" '.[] | select((.relPath | sub(".*/"; "")) == $n) | .relPath' \
      | head -1)
    if [[ -n "$relpath" ]]; then
      path="$SKILLSHARE_ROOT/$relpath"
      if [[ -d "$path" ]]; then
        echo "$path"
        return 0
      fi
    fi
  fi

  # 2. SKILLSHARE_ROOT directory scan (substring match on dir name)
  local match
  match=$(find "$SKILLSHARE_ROOT" -maxdepth 4 -type d \
    \( -name "$name" -o -name "*__${name}" -o -name "*${name}" \) 2>/dev/null \
    | head -1)
  if [[ -n "$match" && -d "$match" ]]; then
    echo "$match"
    return 0
  fi

  return 1
}

# ---------- main loop ----------

declare -a created skipped wrong_target missing solid_file

for skill in $skills; do
  src=$(resolve_source "$skill" || true)
  if [[ -z "$src" ]]; then
    missing+=("$skill")
    continue
  fi
  for d in "${TARGET_DIRS[@]}"; do
    link="$d/$skill"
    if [[ -L "$link" ]]; then
      cur=$(readlink "$link")
      if [[ "$cur" == "$src" ]]; then
        skipped+=("$link")
      else
        wrong_target+=("$link (currently → $cur, expected $src)")
      fi
      continue
    fi
    if [[ -e "$link" ]]; then
      solid_file+=("$link")
      continue
    fi
    ln -s "$src" "$link"
    created+=("$link")
  done
done

# ---------- report ----------

echo "=== prepare.sh summary ==="
echo "Project:        $PROJECT_ROOT"
echo "Sentinel:       $SENTINEL_FILE"
echo "Skillshare:     $SKILLSHARE_ROOT"
echo "Skills wanted:  $(echo "$skills" | wc -w | tr -d ' ')"
echo "Created:        ${#created[@]}"
echo "Already OK:     ${#skipped[@]}"

exit_code=0

if [[ ${#wrong_target[@]} -gt 0 ]]; then
  echo ""
  echo "WARN: ${#wrong_target[@]} link(s) point to unexpected source — leaving as-is:"
  printf '  - %s\n' "${wrong_target[@]}"
  exit_code=2
fi

if [[ ${#solid_file[@]} -gt 0 ]]; then
  echo ""
  echo "ERROR: ${#solid_file[@]} path(s) exist as non-symlink file — please remove manually:"
  printf '  - %s\n' "${solid_file[@]}"
  exit_code=2
fi

if [[ ${#missing[@]} -gt 0 ]]; then
  echo ""
  echo "MISSING source for ${#missing[@]} skill(s):"
  printf '  - %s\n' "${missing[@]}"
  echo ""
  echo "Hint: install / sync skillshare on this machine:"
  echo "  brew install skillshare   # or your package manager"
  echo "  skillshare sync"
  echo "or set SKILLSHARE_ROOT to where your skill sources live."
  exit_code=2
fi

exit $exit_code
